// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synker.Persistence;

namespace Synker.Persistence.Migrations
{
    [DbContext(typeof(SynkerDbContext))]
    [Migration("20190514222020_addMedias")]
    partial class addMedias
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Synker.Domain.Entities.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DisplayName");

                    b.Property<bool>("Enabled");

                    b.Property<string>("Labels");

                    b.Property<byte>("MediaType");

                    b.Property<long?>("PlaylistId");

                    b.Property<int>("Position");

                    b.Property<string>("TvgId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TvgId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Synker.Domain.Entities.Playlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<byte>("State");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Synker.Domain.Entities.PlaylistDataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<short>("PlaylistDataSourceFormat");

                    b.Property<byte>("State");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlaylistDataSources");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PlaylistDataSource");
                });

            modelBuilder.Entity("Synker.Domain.Entities.Tvg", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aspect_ratio");

                    b.Property<string>("Audio_track");

                    b.Property<string>("Logo");

                    b.Property<string>("Name");

                    b.Property<string>("Shift");

                    b.Property<string>("TvgIdentify");

                    b.Property<string>("TvgSiteSource");

                    b.HasKey("Id");

                    b.ToTable("Tvg");
                });

            modelBuilder.Entity("Synker.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Synker.Domain.Entities.M3UPlaylistDataSource", b =>
                {
                    b.HasBaseType("Synker.Domain.Entities.PlaylistDataSource");

                    b.HasDiscriminator().HasValue("M3UPlaylistDataSource");
                });

            modelBuilder.Entity("Synker.Domain.Entities.XtreamPlaylistDataSource", b =>
                {
                    b.HasBaseType("Synker.Domain.Entities.PlaylistDataSource");

                    b.HasDiscriminator().HasValue("XtreamPlaylistDataSource");
                });

            modelBuilder.Entity("Synker.Domain.Entities.Media", b =>
                {
                    b.HasOne("Synker.Domain.Entities.Playlist", "Playlist")
                        .WithMany("Medias")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Synker.Domain.Entities.Tvg", "Tvg")
                        .WithMany()
                        .HasForeignKey("TvgId");

                    b.OwnsOne("Synker.Domain.Entities.Core.UriAddress", "Url", b1 =>
                        {
                            b1.Property<long>("MediaId");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("MediaId");

                            b1.ToTable("Medias");

                            b1.HasOne("Synker.Domain.Entities.Media")
                                .WithOne("Url")
                                .HasForeignKey("Synker.Domain.Entities.Core.UriAddress", "MediaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Synker.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("Synker.Domain.Entities.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Synker.Domain.Entities.PlaylistDataSource", b =>
                {
                    b.HasOne("Synker.Domain.Entities.User", "User")
                        .WithMany("PlaylistDataSources")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Synker.Domain.Entities.M3UPlaylistDataSource", b =>
                {
                    b.OwnsOne("Synker.Domain.Entities.Core.UriAddress", "Uri", b1 =>
                        {
                            b1.Property<long>("M3UPlaylistDataSourceId");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("M3UPlaylistDataSourceId");

                            b1.ToTable("PlaylistDataSources");

                            b1.HasOne("Synker.Domain.Entities.M3UPlaylistDataSource")
                                .WithOne("Uri")
                                .HasForeignKey("Synker.Domain.Entities.Core.UriAddress", "M3UPlaylistDataSourceId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Synker.Domain.Entities.XtreamPlaylistDataSource", b =>
                {
                    b.OwnsOne("Synker.Domain.Entities.Core.BasicAuthentication", "Authentication", b1 =>
                        {
                            b1.Property<long>("XtreamPlaylistDataSourceId");

                            b1.Property<string>("Password")
                                .HasMaxLength(255);

                            b1.Property<string>("User")
                                .IsRequired()
                                .HasMaxLength(255);

                            b1.HasKey("XtreamPlaylistDataSourceId");

                            b1.ToTable("PlaylistDataSources");

                            b1.HasOne("Synker.Domain.Entities.XtreamPlaylistDataSource")
                                .WithOne("Authentication")
                                .HasForeignKey("Synker.Domain.Entities.Core.BasicAuthentication", "XtreamPlaylistDataSourceId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Synker.Domain.Entities.Core.UriAddress", "Server", b1 =>
                        {
                            b1.Property<long>("XtreamPlaylistDataSourceId");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("XtreamPlaylistDataSourceId");

                            b1.ToTable("PlaylistDataSources");

                            b1.HasOne("Synker.Domain.Entities.XtreamPlaylistDataSource")
                                .WithOne("Server")
                                .HasForeignKey("Synker.Domain.Entities.Core.UriAddress", "XtreamPlaylistDataSourceId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
