//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using Xunit;

[assembly: CollectionBehavior(DisableTestParallelization = true)]
[assembly: TestCaseOrderer("Xunit.Extensions.Ordering.TestCaseOrderer", "Xunit.Extensions.Ordering")]
[assembly: TestCollectionOrderer("Xunit.Extensions.Ordering.CollectionOrderer", "Xunit.Extensions.Ordering")]
[assembly: Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactoryContentRootAttribute("Synker.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "C:\\Users\\heni.fazzani\\source\\repos\\Synker.Api\\Synker.Api", "Synker.Api.csproj", "0")]
[assembly: Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactoryContentRootAttribute("Synker.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "C:\\Users\\heni.fazzani\\source\\repos\\Synker.Api\\Synker.Application", "Synker.Application.csproj", "0")]
[assembly: Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactoryContentRootAttribute("Synker.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "C:\\Users\\heni.fazzani\\source\\repos\\Synker.Api\\Synker.Common", "Synker.Common.csproj", "0")]
[assembly: Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactoryContentRootAttribute("Synker.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "C:\\Users\\heni.fazzani\\source\\repos\\Synker.Api\\Synker.Domain", "Synker.Domain.csproj", "0")]
[assembly: Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactoryContentRootAttribute("Synker.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "C:\\Users\\heni.fazzani\\source\\repos\\Synker.Api\\Synker.Infrastructure", "Synker.Infrastructure.csproj", "0")]
[assembly: Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactoryContentRootAttribute("Synker.Persistence, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "C:\\Users\\heni.fazzani\\source\\repos\\Synker.Api\\Synker.Persistence", "Synker.Persistence.csproj", "0")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Synker")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Synker.Api.FunctionalTests")]
[assembly: System.Reflection.AssemblyTitleAttribute("Synker.Api.FunctionalTests")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

